### ISSUE TITLE
Implement Phalcode Support Backend (Crashes)

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#149]
**Is your feature request related to a problem? Please describe.**
We have registered a small amount of app crashes in the past days and i don't know what caused them. Also i would like an additional feedback channel for our app.

![image](https://github.com/Phalcode/gamevault-app/assets/22225051/3335d936-c77c-401a-8d80-a471dd43cae9)

**Describe the solution you'd like**
I would like the app to report crashes to our Phalcode Support Backend again like it did on Watchtower.

## Todos
- [x] Autosend Crash Reports to the Phalcode Support Backend
- [x] Implement "Don't send Crash Reports to Phalcode" Toggle in the Settings (Default Off)
- [x] Tests if the Discord Notifications for the Phalcode Support Backend arrive.

**Comment by Yelo420** [comment]
Added new Exception Window where you can choose whether to send a crash report or not
