### ISSUE TITLE
Allow Admin to Backup/Export and Import Backend DB to allow for easy disaster recovery, manual migrations, etc.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#253]
I've needed to move my docker containers around in the past as well as the database backend (also containerized) and it always nice when an application has a built-in backup/recover, export/import option.

I'm thinking a spot in the admin section could have a simple "Backup Server"/"Export" button that allows the user to download a full backup to their computer. An accompanying "Restore from Backup"/"Import" button that the user can use to upload to the backend server would also be nice.

**Describe alternatives you've considered**
I could always manually backup the DB tables and such. But manual backup processes are tedious and a more casual admin will never do them. A simple way to generate backups and restore from them would go a long way to helping admins of all skill levels manage their own gamevault server.

What do you think?

**Comment by Alfagun74** [comment]
We appreciate your idea and would like to create an Export and Import API. 

This API will perform a "pg_dump" and "pg_restore" on the server for PostgreSQL databases, and for SQLITE databases, it will simply copy/replace the SQLite file.
It's important to note that this API will only be accessible to ADMINS.

Additionally, since this is a high-vulnerability API, it will request the "DB_PASSWORD" Environment Variable set on the server before allowing any export or import actions. This ensures that only users with FULL administrative privileges can initiate these processes. The downloaded file will be an unencrypted full database dump, and when restoring, it will overwrite any existing data without hesitation.

If you wish, you can automate this API by creating a separate ADMIN-role user for your automation needs. However, the decision to do so is up to you.

## TODO:

- [ ] Create an Export and Import API to backup and restore the database.
  - [ ] Implement "pg_dump" and "pg_restore" for PostgreSQL databases.
  - [ ] Enable copying/replacing of SQLite files for SQLITE databases.
- [ ] Restrict API access to ADMINS only.
- [ ] Ensure that the "DB_PASSWORD" Environment Variable is required additionally for authentication.
- [ ] Documentation
  - [ ] Document that downloaded files will be unencrypted full database dumps.
  - [ ] Document that restoring will overwrite existing data without hesitation.
  - [ ] Document you can automate the API by creating a separate ADMIN-role user for automation purposes

**Comment by Kudjo-Grand** [comment]
This sounds PERFECT! 

Also, great thinking about requiring the DB password to ensure the Admin is a "Super Admin". Makes perfect sense.

Can't wait to see and I'll try it out when it's live.

**Comment by Alfagun74** [comment]
Everything is going well so far. Backup and Restore for SQLITE is working perfectly. As for Postgres, the restoration is a bit shaky at the moment, but I'm actively working on it. I plan to include these improvements in version 8.0.0.

**Comment by Yelo420** [comment]
Backup/Restore is implemented in the Admin Tab and will be available with version 1.7.0

**Comment by Kudjo-Grand** [comment]
Woohoo! 🙌 
I'll test it as soon as it's released and report back here.

**Comment by Alfagun74** [comment]
Documented on https://gamevau.lt/docs/server-docs/backup-and-restore

Will roll out on server v8 and app v1.7
