### ISSUE TITLE
ROM / Emulation Support

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#269]
**Exploring GameVault as a Retro Game Management and Emulation Solution**

**Background:**
Our community is home to numerous retro game enthusiasts, and we're considering the possibility of integrating GameVault as both a ROM manager and an emulator.

**Current Status:**
At present, there is no detailed plan in place, and some preliminary research is needed to address this endeavor.

**To-Do List:**
- [ ] Investigate the availability of retro gaming platforms and consoles on RAWG.
- [ ] Implement game types and develop a game type detection system for titles on these platforms.
- [ ] Explore the integration of an emulator, such as emulatorjs, into GameVault.
- [ ] Test and confirm the ability to launch and play ROMs directly from within GameVault.

**Comment by ShadowPeo** [comment]
Perhaps do not need to re-invent the wheel here. Integration might be the name of the game

https://github.com/linuxserver/emulatorjs
https://hub.docker.com/r/linuxserver/emulatorjs

**Comment by Alfagun74** [comment]
@ShadowPeo ticket literally says

> Explore the integration of an emulator, such as emulatorjs, into GameVault.

**Comment by ShadowPeo** [comment]
@Alfagun74 , Huh, so it does, Totally missed it

**Comment by Alfagun74** [comment]
list of platforms rawg supports:
https://gamevau.lt/docs/server-docs/indexing-and-metadata#rawg-platforms

We plan to support them as much as possible aswell.

**Comment by wiseoxejah** [comment]
Would you also consider the option for emulator distribution rather than just server side emulation? I'd love to be able to upload emulator packages independently. Maybe a text file within the archive could specify the location for roms. Then you'd be able to download roms and have them moved into the specified folder similar to (W_P).

Feel free to let me know if this is a terrible idea.

**Comment by MoSattler** [comment]
> Would you also consider the option for emulator distribution rather than just server side emulation? 

Personally I am looking for the "Steam-for-Roms" experience. As in, have my devices (RetroPie, RetroArch) being able to download the games from my self hosted backend, and then just play them. Extra points for sync of safe games!

**Comment by jedinjapan** [comment]
To echo some of the comments here: The emulatorjs project covers the goal of server-side in-browser emulation just fine on its own, and has multiple other deployments. Integrating that project directly into Gamevault is just duct taping two different projects together and, in my opinion, offers little value to what is supposed to be a library _management_ and _deployment_ app. This in fact would drive me _away_ from using Gamevault to manage things, as I already have an emulatorjs instance setup and this only serves to complicate that instance while also diverting the focus of this tool, and ensuring it will never properly manage emulators.

It distracts from the idea that this is supposed to be a library resource for those connecting to it. Similar to PC titles, consider associating ROMs with their emulator, and using Gamevault to manage and distribute a ROM/Emulator pair based on a script that can place them in the appropriate folder, and skip the emulator deployment if it is detected. This would be absolutely a game changer in terms of simplicity for non-technical family members. This could allow a user to host their Gamevault instance of ROMs in the same manner they host their PC titles, and easily setup single titles on new systems, including allowing deployment of different emulators based on the platform accessing the vault, all without migrating the entire ROM collection or without the latency/lag or limitations of in-browser emulation. This would make instant co-op in emulated titles infinitely easier when one has guests.

Often times with newer emulation titles need specific tweaks and setups to function, and using Gamevault to make these into "packages" for your family could make the process painless.

**Comment by Alfagun74** [comment]
@jedinjapan Thanks for the feedback! To clarify: We currently plan that EmulatorJS is just an optional add-on/feature for the client and not the main focus in this milestone. It’s a way we want to offer to emulate without any extra software, but you’re not required to use it.

It is just a starting point, and we will definitely be exploring deeper integration with existing emulators. We may even monetize the EmulatorJS part, while keeping external emulator integrations free. 

I think that's a good compromise to offer our GameVault+ users more features, without taking away too much from the free users, to keep the project alive and all that.

**Comment by Sixdd6** [comment]
Just throwing my two cents in here. The way I currently handle emulated systems is by packaging a LaunchBox instance with the emulator/roms I want to emulate. I also wouldn't use an emulatorjs instance since it doesn't (to my knowledge) run more complex systems like PS2 and Xbox which are my current goto for older games. I'd much rather have something like the current PC implementation where I can setup an emulator in GameVault and set an install path for the games, then the GameVault client could launch the games in a seamless way. Basically I want to be able to launch emulated games directly from GV without having to see any consoles or emulators in between. Super bonus points if I could somehow use an overlay or button combo to close the game when I'm done playing, maybe an AHK script could accomplish this.

Just some ideas and feedback, keep it up guys you're doing great.
