### ISSUE TITLE
Killing GameVault process should remain Download Progress

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#415]
**Problem:** Downloads in GameVault currently restart from the beginning if interrupted by crashes, network issues, or user actions. This leads to wasted bandwidth and a poor user experience.

**To-Do:**

* [x] Implement a checkpoint download system that saves progress periodically (e.g., every 1 MB).
* [x] Update download logic to resume from the latest checkpoint upon interruption.
* [ ] Remove the "Are you sure you want to quit with downloads running?" prompt (once checkpointing is implemented).

**Comment by ronaldmcdonald67555** [comment]
this is tarabel

**Comment by Alfagun74** [comment]
> this is tarabel

Would you mind to elaborate

**Comment by Yelo420** [comment]
Implemented
